<li><a href="index.php">Home</a></li>
<li><a href="about_us.php">About Us</a> </li>
<li><a href="clientele.php">Clientele</a> </li>
<li><a href="services.php">Services</a></li>
<li><a href="upcoming_events.php">Upcoming Events</a></li>
<!--<li><a href="our_wings.php">Our Wings</a></li>-->
<li><a href="testimonials.php">Testimonials</a></li>
<li><a href="photo_gallery.php">Photo Gallery</a></li>
<li><a href="video_gallery.php">Video Gallery</a></li>
<li><a href="contact_us.php">Contact Us</a></li>